const emojis = [
  { emoji: '😀', name: 'Smile' },
  { emoji: '🐶', name: 'Dog' },
  { emoji: '🌮', name: 'Taco' },
  { emoji: '🎉', name: 'Party Popper' },
  { emoji: '🍕', name: 'Pizza' },
  { emoji: '🚀', name: 'Rocket' },
  { emoji: '🌈', name: 'Rainbow' },
  { emoji: '🎈', name: 'Balloon' },
  { emoji: '🐱', name: 'Cat' },
  { emoji: '🍔', name: 'Hamburger' },
  { emoji: '🚗', name: 'Car' },
  { emoji: '🌟', name: 'Star' },
  { emoji: '🍦', name: 'Ice Cream' },
  { emoji: '🎸', name: 'Guitar' },
  { emoji: '📚', name: 'Book' },
  { emoji: '🌸', name: 'Flower' },
  { emoji: '🎩', name: 'Top Hat' },
  { emoji: '🍩', name: 'Donut' },
  { emoji: '🏆', name: 'Trophy' },
  { emoji: '🎨', name: 'Palette' },
  { emoji: '📷', name: 'Camera' },
  { emoji: '🎤', name: 'Microphone' },
  { emoji: '🦄', name: 'Unicorn' },
  { emoji: '🏀', name: 'Basketball' },
  { emoji: '🌊', name: 'Wave' },
  { emoji: '🍓', name: 'Strawberry' },
  { emoji: '🚲', name: 'Bicycle' },
  { emoji: '🎹', name: 'Piano' },
  { emoji: '🌻', name: 'Sunflower' },
  { emoji: '🎲', name: 'Dice' },
  { emoji: '🍎', name: 'Apple' },
  { emoji: '🐻', name: 'Bear' },
  { emoji: '🚁', name: 'Helicopter' },
  { emoji: '🍭', name: 'Lollipop' },
  { emoji: '📱', name: 'Mobile Phone' },
  { emoji: '🎧', name: 'Headphones' },
  { emoji: '🌙', name: 'Moon' },
  { emoji: '🍇', name: 'Grapes' },
  { emoji: '🏠', name: 'House' },
  { emoji: '🔑', name: 'Key' },
  { emoji: '🎯', name: 'Bullseye' },
  { emoji: '🍟', name: 'French Fries' },
  { emoji: '🐦', name: 'Bird' },
  { emoji: '🚢', name: 'Ship' },
  { emoji: '🌄', name: 'Sunrise' },
  { emoji: '🌈', name: 'Rainbow' },
  { emoji: '🐠', name: 'Fish' },
  { emoji: '🎈', name: 'Balloon' },
  { emoji: '🎃', name: 'Jack-O-Lantern' },
  { emoji: '🎁', name: 'Gift' },
  { emoji: '🌞', name: 'Sun' },
  { emoji: '🚀', name: 'Rocket' },
  { emoji: '🌵', name: 'Cactus' },
  { emoji: '🎭', name: 'Mask' },
  { emoji: '🐯', name: 'Tiger' },
  { emoji: '🎥', name: 'Movie Camera' },
  { emoji: '🍪', name: 'Cookie' },
  { emoji: '🏰', name: 'Castle' },
  { emoji: '🌍', name: 'Globe' },
  { emoji: '🔥', name: 'Fire' },
  { emoji: '🍉', name: 'Watermelon' },
  { emoji: '🦁', name: 'Lion' },
  { emoji: '🌊', name: 'Wave' },
  { emoji: '🍩', name: 'Donut' },
  { emoji: '🚗', name: 'Car' },
  { emoji: '📚', name: 'Book' },
  { emoji: '🎻', name: 'Violin' },
  { emoji: '🌺', name: 'Hibiscus' },
  { emoji: '🏓', name: 'Ping Pong' },
  { emoji: '🍔', name: 'Hamburger' },
  { emoji: '🎮', name: 'Video Game' },
  { emoji: '🚲', name: 'Bicycle' },
  { emoji: '📷', name: 'Camera' },
  { emoji: '🐵', name: 'Monkey' },
  { emoji: '🎤', name: 'Microphone' },
  { emoji: '🌴', name: 'Palm Tree' },
  { emoji: '🍕', name: 'Pizza' },
  { emoji: '🎨', name: 'Palette' },
  { emoji: '🐬', name: 'Dolphin' },
  { emoji: '🏈', name: 'American Football' },
  { emoji: '🎧', name: 'Headphones' },
  { emoji: '🌻', name: 'Sunflower' },
  { emoji: '🦄', name: 'Unicorn' },
  { emoji: '🍎', name: 'Apple' },
  { emoji: '🎸', name: 'Guitar' },
  { emoji: '🍦', name: 'Ice Cream' },
  { emoji: '🐶', name: 'Dog' },
  { emoji: '🍓', name: 'Strawberry' },
  { emoji: '🎉', name: 'Party Popper' },
  { emoji: '🌮', name: 'Taco' },
  { emoji: '🎈', name: 'Balloon' },
]

module.exports = {
  emojis,
}
